name: "PR checks for dev"

on:
  pull_request:
    branches:
      - dev
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

jobs:
  unit_tests:
    name: "Execute unit tests"
    if: ${{ github.event.pull_request.draft == false }}
    uses: ./.github/workflows/run_tests.yml
